# Generated by Django 5.0.3 on 2024-03-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Product_id', models.IntegerField(unique=True)),
                ('Description', models.CharField(max_length=1000)),
                ('price', models.FloatField(max_length=30)),
                ('img', models.ImageField(upload_to='images/')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
    ]
