# Generated by Django 5.0.3 on 2024-03-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('c_details', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlistt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('wl_details', models.ManyToManyField(related_name='wishlist', to='app1.product')),
            ],
        ),
    ]
