# Generated by Django 5.0.3 on 2024-03-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
